module.exports = [
    {
        "title": "But",
        "artist": "Cari Lekebusch",
        "album": "debitis",
        "label": "Star Dub",
        "year": 1990,
        "genre": "Minimal House",
        "producer": "Andreas Carlson",
        "key": "6A",
        "bpm": 107
    },
    {
        "title": "I",
        "artist": "Cari Lekebusch",
        "album": "debitis",
        "label": "Star Dub",
        "year": 1990,
        "genre": "Minimal House",
        "producer": "LRG",
        "key": "12A",
        "bpm": 120
    },
    {
        "title": "must",
        "artist": "Cari Lekebusch",
        "album": "debitis",
        "label": "Star Dub",
        "year": 1990,
        "genre": "Minimal House",
        "producer": "Martin Solveig",
        "key": "7B",
        "bpm": 100
    },
    {
        "title": "explain",
        "artist": "Cari Lekebusch",
        "album": "debitis",
        "label": "Star Dub",
        "year": 1990,
        "genre": "Minimal House",
        "producer": "Martin Solveig",
        "key": "8B",
        "bpm": 105
    },
    {
        "title": "to",
        "artist": "Cari Lekebusch",
        "album": "debitis",
        "label": "Star Dub",
        "year": 1990,
        "genre": "Minimal House",
        "producer": "Daniel G",
        "key": "8B",
        "bpm": 100
    },
    {
        "title": "you",
        "artist": "Cari Lekebusch",
        "album": "rerum",
        "label": "Echochord",
        "year": 1990,
        "genre": "House",
        "producer": "Sam B",
        "key": "7B",
        "bpm": 120
    },
    {
        "title": "how",
        "artist": "Cari Lekebusch",
        "album": "rerum",
        "label": "Echochord",
        "year": 1990,
        "genre": "House",
        "producer": "Andreas Carlson",
        "key": "7B",
        "bpm": 120
    },
    {
        "title": "all",
        "artist": "Cari Lekebusch",
        "album": "rerum",
        "label": "Echochord",
        "year": 1990,
        "genre": "House",
        "producer": "Andreas Carlson",
        "key": "8B",
        "bpm": 107
    },
    {
        "title": "this",
        "artist": "Cari Lekebusch",
        "album": "rerum",
        "label": "Echochord",
        "year": 1990,
        "genre": "House",
        "producer": "Martin Solveig",
        "key": "12A",
        "bpm": 100
    },
    {
        "title": "mistaken",
        "artist": "Cari Lekebusch",
        "album": "rerum",
        "label": "Echochord",
        "year": 1990,
        "genre": "House",
        "producer": "LRG",
        "key": "7B",
        "bpm": 100
    },
    {
        "title": "idea",
        "artist": "Cari Lekebusch",
        "album": "necessitatibus",
        "label": "Porslin Records",
        "year": 2005,
        "genre": "House",
        "producer": "LRG",
        "key": "6A",
        "bpm": 100
    },
    {
        "title": "of",
        "artist": "Cari Lekebusch",
        "album": "necessitatibus",
        "label": "Porslin Records",
        "year": 2005,
        "genre": "House",
        "producer": "Martin Solveig",
        "key": "7B",
        "bpm": 120
    },
    {
        "title": "denouncing",
        "artist": "Cari Lekebusch",
        "album": "necessitatibus",
        "label": "Porslin Records",
        "year": 2005,
        "genre": "House",
        "producer": "Martin Solveig",
        "key": "7B",
        "bpm": 100
    },
    {
        "title": "pleasure",
        "artist": "Cari Lekebusch",
        "album": "necessitatibus",
        "label": "Porslin Records",
        "year": 2005,
        "genre": "House",
        "producer": "Andreas Carlson",
        "key": "8B",
        "bpm": 120
    },
    {
        "title": "and",
        "artist": "Cari Lekebusch",
        "album": "necessitatibus",
        "label": "Porslin Records",
        "year": 2005,
        "genre": "House",
        "producer": "Andreas Carlson",
        "key": "6A",
        "bpm": 105
    },
    {
        "title": "praising",
        "artist": "Cari Lekebusch",
        "album": "saepe",
        "label": "Porslin Records",
        "year": 2000,
        "genre": "Minimal House",
        "producer": "Sam B",
        "key": "7B",
        "bpm": 107
    },
    {
        "title": "pain",
        "artist": "Cari Lekebusch",
        "album": "saepe",
        "label": "Porslin Records",
        "year": 2000,
        "genre": "Minimal House",
        "producer": "Andreas Carlson",
        "key": "6A",
        "bpm": 120
    },
    {
        "title": "was",
        "artist": "Cari Lekebusch",
        "album": "saepe",
        "label": "Porslin Records",
        "year": 2000,
        "genre": "Minimal House",
        "producer": "Daniel G",
        "key": "6A",
        "bpm": 107
    },
    {
        "title": "born",
        "artist": "Cari Lekebusch",
        "album": "saepe",
        "label": "Porslin Records",
        "year": 2000,
        "genre": "Minimal House",
        "producer": "Martin Solveig",
        "key": "8B",
        "bpm": 107
    },
    {
        "title": "and",
        "artist": "Cari Lekebusch",
        "album": "saepe",
        "label": "Porslin Records",
        "year": 2000,
        "genre": "Minimal House",
        "producer": "Martin Solveig",
        "key": "8B",
        "bpm": 100
    },
    {
        "title": "I",
        "artist": "Cari Lekebusch",
        "album": "eveniet",
        "label": "Echochord",
        "year": 1990,
        "genre": "Minimal House",
        "producer": "LRG",
        "key": "8B",
        "bpm": 120
    },
    {
        "title": "will",
        "artist": "Cari Lekebusch",
        "album": "eveniet",
        "label": "Echochord",
        "year": 1990,
        "genre": "Minimal House",
        "producer": "Martin Solveig",
        "key": "6A",
        "bpm": 107
    },
    {
        "title": "give",
        "artist": "Cari Lekebusch",
        "album": "eveniet",
        "label": "Echochord",
        "year": 1990,
        "genre": "Minimal House",
        "producer": "Martin Solveig",
        "key": "8B",
        "bpm": 120
    },
    {
        "title": "you",
        "artist": "Kerri Chandler",
        "album": "eveniet",
        "label": "Echochord",
        "year": 1990,
        "genre": "Minimal House",
        "producer": "LRG",
        "key": "8B",
        "bpm": 120
    },
    {
        "title": "a",
        "artist": "Kerri Chandler",
        "album": "eveniet",
        "label": "Echochord",
        "year": 1990,
        "genre": "Minimal House",
        "producer": "LRG",
        "key": "6A",
        "bpm": 107
    },
    {
        "title": "complete",
        "artist": "Kerri Chandler",
        "album": "voluptates",
        "label": "Echochord",
        "year": 2005,
        "genre": "Acid",
        "producer": "Max Martin",
        "key": "7B",
        "bpm": 105
    },
    {
        "title": "account",
        "artist": "Kerri Chandler",
        "album": "voluptates",
        "label": "Echochord",
        "year": 2005,
        "genre": "Acid",
        "producer": "Max Martin",
        "key": "12A",
        "bpm": 120
    },
    {
        "title": "of",
        "artist": "Kerri Chandler",
        "album": "voluptates",
        "label": "Echochord",
        "year": 2005,
        "genre": "Acid",
        "producer": "Martin Solveig",
        "key": "6A",
        "bpm": 105
    },
    {
        "title": "the",
        "artist": "Kerri Chandler",
        "album": "voluptates",
        "label": "Echochord",
        "year": 2005,
        "genre": "Acid",
        "producer": "Andreas Carlson",
        "key": "12A",
        "bpm": 100
    },
    {
        "title": "system,",
        "artist": "Kerri Chandler",
        "album": "voluptates",
        "label": "Echochord",
        "year": 2005,
        "genre": "Acid",
        "producer": "Sam B",
        "key": "12A",
        "bpm": 120
    },
    {
        "title": "and",
        "artist": "Kerri Chandler",
        "album": "repudiandae",
        "label": "Berg Audio",
        "year": 1995,
        "genre": "Techno",
        "producer": "Daniel G",
        "key": "7B",
        "bpm": 105
    },
    {
        "title": "expound",
        "artist": "Kerri Chandler",
        "album": "repudiandae",
        "label": "Berg Audio",
        "year": 1995,
        "genre": "Techno",
        "producer": "Andreas Carlson",
        "key": "12A",
        "bpm": 120
    },
    {
        "title": "the",
        "artist": "Kerri Chandler",
        "album": "repudiandae",
        "label": "Berg Audio",
        "year": 1995,
        "genre": "Techno",
        "producer": "LRG",
        "key": "6A",
        "bpm": 105
    },
    {
        "title": "actual",
        "artist": "Kerri Chandler",
        "album": "repudiandae",
        "label": "Berg Audio",
        "year": 1995,
        "genre": "Techno",
        "producer": "Max Martin",
        "key": "7B",
        "bpm": 105
    },
    {
        "title": "teachings",
        "artist": "Kerri Chandler",
        "album": "repudiandae",
        "label": "Berg Audio",
        "year": 1995,
        "genre": "Techno",
        "producer": "Martin Solveig",
        "key": "7B",
        "bpm": 120
    },
    {
        "title": "of",
        "artist": "Kerri Chandler",
        "album": "molestiae",
        "label": "Star Dub",
        "year": 1990,
        "genre": "Acid",
        "producer": "Adam A",
        "key": "12A",
        "bpm": 120
    },
    {
        "title": "the",
        "artist": "Kerri Chandler",
        "album": "molestiae",
        "label": "Star Dub",
        "year": 1990,
        "genre": "Acid",
        "producer": "Adam A",
        "key": "7B",
        "bpm": 105
    },
    {
        "title": "great",
        "artist": "Kerri Chandler",
        "album": "molestiae",
        "label": "Star Dub",
        "year": 1990,
        "genre": "Acid",
        "producer": "Daniel G",
        "key": "12A",
        "bpm": 100
    },
    {
        "title": "explorer",
        "artist": "Kerri Chandler",
        "album": "molestiae",
        "label": "Star Dub",
        "year": 1990,
        "genre": "Acid",
        "producer": "Martin Solveig",
        "key": "8B",
        "bpm": 100
    },
    {
        "title": "of",
        "artist": "Kerri Chandler",
        "album": "molestiae",
        "label": "Star Dub",
        "year": 1990,
        "genre": "Acid",
        "producer": "Sam B",
        "key": "8B",
        "bpm": 105
    },
    {
        "title": "the",
        "artist": "Kerri Chandler",
        "album": "recusandae",
        "label": "Berg Audio",
        "year": 1990,
        "genre": "House",
        "producer": "Martin Solveig",
        "key": "8B",
        "bpm": 107
    },
    {
        "title": "truth,",
        "artist": "Kerri Chandler",
        "album": "recusandae",
        "label": "Berg Audio",
        "year": 1990,
        "genre": "House",
        "producer": "Adam A",
        "key": "7B",
        "bpm": 107
    },
    {
        "title": "the",
        "artist": "Kerri Chandler",
        "album": "recusandae",
        "label": "Berg Audio",
        "year": 1990,
        "genre": "House",
        "producer": "Andreas Carlson",
        "key": "6A",
        "bpm": 120
    },
    {
        "title": "master-builder",
        "artist": "Kerri Chandler",
        "album": "recusandae",
        "label": "Berg Audio",
        "year": 1990,
        "genre": "House",
        "producer": "Max Martin",
        "key": "12A",
        "bpm": 120
    },
    {
        "title": "of",
        "artist": "Kerri Chandler",
        "album": "recusandae",
        "label": "Berg Audio",
        "year": 1990,
        "genre": "House",
        "producer": "Max Martin",
        "key": "8B",
        "bpm": 100
    },
    {
        "title": "human",
        "artist": "Kerri Chandler",
        "album": "Itaque",
        "label": "Porslin Records",
        "year": 2005,
        "genre": "Minimal House",
        "producer": "Sam B",
        "key": "7B",
        "bpm": 100
    },
    {
        "title": "happiness.",
        "artist": "Fluxion",
        "album": "Itaque",
        "label": "Porslin Records",
        "year": 2005,
        "genre": "Minimal House",
        "producer": "Max Martin",
        "key": "6A",
        "bpm": 120
    },
    {
        "title": "No",
        "artist": "Fluxion",
        "album": "Itaque",
        "label": "Porslin Records",
        "year": 2005,
        "genre": "Minimal House",
        "producer": "Daniel G",
        "key": "12A",
        "bpm": 120
    },
    {
        "title": "one",
        "artist": "Fluxion",
        "album": "Itaque",
        "label": "Porslin Records",
        "year": 2005,
        "genre": "Minimal House",
        "producer": "Martin Solveig",
        "key": "6A",
        "bpm": 120
    },
    {
        "title": "rejects,",
        "artist": "Fluxion",
        "album": "Itaque",
        "label": "Porslin Records",
        "year": 2005,
        "genre": "Minimal House",
        "producer": "Andreas Carlson",
        "key": "8B",
        "bpm": 107
    },
    {
        "title": "dislikes,",
        "artist": "Fluxion",
        "album": "earum",
        "label": "Porslin Records",
        "year": 2005,
        "genre": "Techno",
        "producer": "LRG",
        "key": "12A",
        "bpm": 107
    },
    {
        "title": "or",
        "artist": "Fluxion",
        "album": "earum",
        "label": "Porslin Records",
        "year": 2005,
        "genre": "Techno",
        "producer": "Adam A",
        "key": "12A",
        "bpm": 105
    },
    {
        "title": "avoids",
        "artist": "Fluxion",
        "album": "earum",
        "label": "Porslin Records",
        "year": 2005,
        "genre": "Techno",
        "producer": "Martin Solveig",
        "key": "7B",
        "bpm": 100
    },
    {
        "title": "pleasure",
        "artist": "Fluxion",
        "album": "earum",
        "label": "Porslin Records",
        "year": 2005,
        "genre": "Techno",
        "producer": "Andreas Carlson",
        "key": "8B",
        "bpm": 120
    },
    {
        "title": "itself,",
        "artist": "Fluxion",
        "album": "earum",
        "label": "Porslin Records",
        "year": 2005,
        "genre": "Techno",
        "producer": "LRG",
        "key": "7B",
        "bpm": 100
    },
    {
        "title": "because",
        "artist": "Fluxion",
        "album": "rerum",
        "label": "Echochord",
        "year": 2000,
        "genre": "Techno",
        "producer": "Adam A",
        "key": "8B",
        "bpm": 100
    },
    {
        "title": "it",
        "artist": "Fluxion",
        "album": "rerum",
        "label": "Echochord",
        "year": 2000,
        "genre": "Techno",
        "producer": "Adam A",
        "key": "12A",
        "bpm": 105
    },
    {
        "title": "is",
        "artist": "Fluxion",
        "album": "rerum",
        "label": "Echochord",
        "year": 2000,
        "genre": "Techno",
        "producer": "Sam B",
        "key": "6A",
        "bpm": 120
    },
    {
        "title": "pleasure,",
        "artist": "Fluxion",
        "album": "rerum",
        "label": "Echochord",
        "year": 2000,
        "genre": "Techno",
        "producer": "Max Martin",
        "key": "12A",
        "bpm": 100
    },
    {
        "title": "but",
        "artist": "Fluxion",
        "album": "rerum",
        "label": "Echochord",
        "year": 2000,
        "genre": "Techno",
        "producer": "Max Martin",
        "key": "7B",
        "bpm": 100
    },
    {
        "title": "because",
        "artist": "Fluxion",
        "album": "tenetur",
        "label": "Recordeep",
        "year": 1990,
        "genre": "House",
        "producer": "Max Martin",
        "key": "8B",
        "bpm": 107
    },
    {
        "title": "those",
        "artist": "Fluxion",
        "album": "tenetur",
        "label": "Recordeep",
        "year": 1990,
        "genre": "House",
        "producer": "Max Martin",
        "key": "12A",
        "bpm": 100
    },
    {
        "title": "who",
        "artist": "Fluxion",
        "album": "tenetur",
        "label": "Recordeep",
        "year": 1990,
        "genre": "House",
        "producer": "Martin Solveig",
        "key": "6A",
        "bpm": 120
    },
    {
        "title": "do",
        "artist": "Fluxion",
        "album": "tenetur",
        "label": "Recordeep",
        "year": 1990,
        "genre": "House",
        "producer": "Martin Solveig",
        "key": "7B",
        "bpm": 105
    },
    {
        "title": "not",
        "artist": "Fluxion",
        "album": "tenetur",
        "label": "Recordeep",
        "year": 1990,
        "genre": "House",
        "producer": "Andreas Carlson",
        "key": "8B",
        "bpm": 120
    },
    {
        "title": "know",
        "artist": "Fluxion",
        "album": "sapiente",
        "label": "Berg Audio",
        "year": 2000,
        "genre": "House",
        "producer": "Sam B",
        "key": "8B",
        "bpm": 107
    },
    {
        "title": "how",
        "artist": "Fluxion",
        "album": "sapiente",
        "label": "Berg Audio",
        "year": 2000,
        "genre": "House",
        "producer": "Adam A",
        "key": "6A",
        "bpm": 120
    },
    {
        "title": "to",
        "artist": "Fluxion",
        "album": "sapiente",
        "label": "Berg Audio",
        "year": 2000,
        "genre": "House",
        "producer": "Sam B",
        "key": "8B",
        "bpm": 120
    },
    {
        "title": "pursue",
        "artist": "Fluxion",
        "album": "sapiente",
        "label": "Berg Audio",
        "year": 2000,
        "genre": "House",
        "producer": "Andreas Carlson",
        "key": "7B",
        "bpm": 100
    },
    {
        "title": "pleasure",
        "artist": "Seb Zito",
        "album": "sapiente",
        "label": "Berg Audio",
        "year": 2000,
        "genre": "House",
        "producer": "Andreas Carlson",
        "key": "8B",
        "bpm": 105
    },
    {
        "title": "rationally",
        "artist": "Seb Zito",
        "album": "delectus",
        "label": "Berg Audio",
        "year": 2000,
        "genre": "Acid",
        "producer": "Max Martin",
        "key": "8B",
        "bpm": 107
    },
    {
        "title": "encounter",
        "artist": "Seb Zito",
        "album": "delectus",
        "label": "Berg Audio",
        "year": 2000,
        "genre": "Acid",
        "producer": "Adam A",
        "key": "12A",
        "bpm": 120
    },
    {
        "title": "consequences",
        "artist": "Seb Zito",
        "album": "delectus",
        "label": "Berg Audio",
        "year": 2000,
        "genre": "Acid",
        "producer": "Adam A",
        "key": "6A",
        "bpm": 107
    },
    {
        "title": "that",
        "artist": "Seb Zito",
        "album": "delectus",
        "label": "Berg Audio",
        "year": 2000,
        "genre": "Acid",
        "producer": "Adam A",
        "key": "6A",
        "bpm": 100
    },
    {
        "title": "are",
        "artist": "Seb Zito",
        "album": "delectus",
        "label": "Berg Audio",
        "year": 2000,
        "genre": "Acid",
        "producer": "Andreas Carlson",
        "key": "12A",
        "bpm": 100
    },
    {
        "title": "extremely",
        "artist": "Seb Zito",
        "album": "reiciendis",
        "label": "Echochord",
        "year": 2000,
        "genre": "Minimal House",
        "producer": "Max Martin",
        "key": "8B",
        "bpm": 105
    },
    {
        "title": "painful.",
        "artist": "Seb Zito",
        "album": "reiciendis",
        "label": "Echochord",
        "year": 2000,
        "genre": "Minimal House",
        "producer": "Sam B",
        "key": "12A",
        "bpm": 105
    },
    {
        "title": "Nor",
        "artist": "Seb Zito",
        "album": "reiciendis",
        "label": "Echochord",
        "year": 2000,
        "genre": "Minimal House",
        "producer": "Andreas Carlson",
        "key": "6A",
        "bpm": 107
    },
    {
        "title": "again",
        "artist": "Seb Zito",
        "album": "reiciendis",
        "label": "Echochord",
        "year": 2000,
        "genre": "Minimal House",
        "producer": "LRG",
        "key": "12A",
        "bpm": 100
    },
    {
        "title": "is",
        "artist": "Seb Zito",
        "album": "reiciendis",
        "label": "Echochord",
        "year": 2000,
        "genre": "Minimal House",
        "producer": "Daniel G",
        "key": "7B",
        "bpm": 107
    },
    {
        "title": "therewho",
        "artist": "Seb Zito",
        "album": "voluptatibus",
        "label": "Recordeep",
        "year": 2005,
        "genre": "Minimal House",
        "producer": "LRG",
        "key": "8B",
        "bpm": 120
    },
    {
        "title": "loves",
        "artist": "Seb Zito",
        "album": "voluptatibus",
        "label": "Recordeep",
        "year": 2005,
        "genre": "Minimal House",
        "producer": "Daniel G",
        "key": "12A",
        "bpm": 107
    },
    {
        "title": "or",
        "artist": "Seb Zito",
        "album": "voluptatibus",
        "label": "Recordeep",
        "year": 2005,
        "genre": "Minimal House",
        "producer": "LRG",
        "key": "6A",
        "bpm": 120
    },
    {
        "title": "pursues",
        "artist": "Seb Zito",
        "album": "voluptatibus",
        "label": "Recordeep",
        "year": 2005,
        "genre": "Minimal House",
        "producer": "LRG",
        "key": "12A",
        "bpm": 105
    },
    {
        "title": "or",
        "artist": "Seb Zito",
        "album": "voluptatibus",
        "label": "Recordeep",
        "year": 2005,
        "genre": "Minimal House",
        "producer": "Andreas Carlson",
        "key": "12A",
        "bpm": 120
    },
    {
        "title": "desires",
        "artist": "Seb Zito",
        "album": "maiores",
        "label": "Berg Audio",
        "year": 1990,
        "genre": "Dub-Techno",
        "producer": "Daniel G",
        "key": "12A",
        "bpm": 107
    },
    {
        "title": "to",
        "artist": "Seb Zito",
        "album": "maiores",
        "label": "Berg Audio",
        "year": 1990,
        "genre": "Dub-Techno",
        "producer": "Andreas Carlson",
        "key": "6A",
        "bpm": 107
    },
    {
        "title": "obtain",
        "artist": "Seb Zito",
        "album": "maiores",
        "label": "Berg Audio",
        "year": 1990,
        "genre": "Dub-Techno",
        "producer": "Sam B",
        "key": "6A",
        "bpm": 107
    },
    {
        "title": "pain",
        "artist": "Seb Zito",
        "album": "maiores",
        "label": "Berg Audio",
        "year": 1990,
        "genre": "Dub-Techno",
        "producer": "LRG",
        "key": "6A",
        "bpm": 100
    },
    {
        "title": "of",
        "artist": "Seb Zito",
        "album": "maiores",
        "label": "Berg Audio",
        "year": 1990,
        "genre": "Dub-Techno",
        "producer": "LRG",
        "key": "6A",
        "bpm": 107
    },
    {
        "title": "itself,",
        "artist": "Seb Zito",
        "album": "alias",
        "label": "Porslin Records",
        "year": 2000,
        "genre": "Acid",
        "producer": "Sam B",
        "key": "8B",
        "bpm": 107
    },
    {
        "title": "because",
        "artist": "Seb Zito",
        "album": "alias",
        "label": "Porslin Records",
        "year": 2000,
        "genre": "Acid",
        "producer": "LRG",
        "key": "7B",
        "bpm": 107
    },
    {
        "title": "it",
        "artist": "Etapp Kyle",
        "album": "alias",
        "label": "Porslin Records",
        "year": 2000,
        "genre": "Acid",
        "producer": "Martin Solveig",
        "key": "12A",
        "bpm": 107
    },
    {
        "title": "is",
        "artist": "Etapp Kyle",
        "album": "alias",
        "label": "Porslin Records",
        "year": 2000,
        "genre": "Acid",
        "producer": "LRG",
        "key": "8B",
        "bpm": 120
    },
    {
        "title": "pain,",
        "artist": "Etapp Kyle",
        "album": "alias",
        "label": "Porslin Records",
        "year": 2000,
        "genre": "Acid",
        "producer": "LRG",
        "key": "6A",
        "bpm": 105
    },
    {
        "title": "but",
        "artist": "Etapp Kyle",
        "album": "consequatur",
        "label": "Recordeep",
        "year": 1995,
        "genre": "Techno",
        "producer": "Max Martin",
        "key": "6A",
        "bpm": 120
    },
    {
        "title": "because",
        "artist": "Etapp Kyle",
        "album": "consequatur",
        "label": "Recordeep",
        "year": 1995,
        "genre": "Techno",
        "producer": "Adam A",
        "key": "7B",
        "bpm": 120
    },
    {
        "title": "occasionally",
        "artist": "Etapp Kyle",
        "album": "consequatur",
        "label": "Recordeep",
        "year": 1995,
        "genre": "Techno",
        "producer": "Andreas Carlson",
        "key": "8B",
        "bpm": 107
    },
    {
        "title": "circumstances",
        "artist": "Etapp Kyle",
        "album": "consequatur",
        "label": "Recordeep",
        "year": 1995,
        "genre": "Techno",
        "producer": "Daniel G",
        "key": "7B",
        "bpm": 100
    },
    {
        "title": "occur",
        "artist": "Etapp Kyle",
        "album": "consequatur",
        "label": "Recordeep",
        "year": 1995,
        "genre": "Techno",
        "producer": "Sam B",
        "key": "7B",
        "bpm": 107
    },
    {
        "title": "in",
        "artist": "Etapp Kyle",
        "album": "easy",
        "label": "Echochord",
        "year": 1990,
        "genre": "House",
        "producer": "Max Martin",
        "key": "12A",
        "bpm": 107
    },
    {
        "title": "which",
        "artist": "Etapp Kyle",
        "album": "easy",
        "label": "Echochord",
        "year": 1990,
        "genre": "House",
        "producer": "LRG",
        "key": "6A",
        "bpm": 107
    },
    {
        "title": "toil",
        "artist": "Etapp Kyle",
        "album": "easy",
        "label": "Echochord",
        "year": 1990,
        "genre": "House",
        "producer": "Daniel G",
        "key": "8B",
        "bpm": 100
    },
    {
        "title": "and",
        "artist": "Etapp Kyle",
        "album": "easy",
        "label": "Echochord",
        "year": 1990,
        "genre": "House",
        "producer": "Max Martin",
        "key": "12A",
        "bpm": 105
    },
    {
        "title": "pain",
        "artist": "Etapp Kyle",
        "album": "easy",
        "label": "Echochord",
        "year": 1990,
        "genre": "House",
        "producer": "Sam B",
        "key": "7B",
        "bpm": 120
    },
    {
        "title": "can",
        "artist": "Etapp Kyle",
        "album": "to",
        "label": "Recordeep",
        "year": 2005,
        "genre": "Techno",
        "producer": "Adam A",
        "key": "8B",
        "bpm": 120
    },
    {
        "title": "procure",
        "artist": "Etapp Kyle",
        "album": "to",
        "label": "Recordeep",
        "year": 2005,
        "genre": "Techno",
        "producer": "Andreas Carlson",
        "key": "12A",
        "bpm": 100
    },
    {
        "title": "him",
        "artist": "Etapp Kyle",
        "album": "to",
        "label": "Recordeep",
        "year": 2005,
        "genre": "Techno",
        "producer": "Andreas Carlson",
        "key": "7B",
        "bpm": 100
    },
    {
        "title": "some",
        "artist": "Etapp Kyle",
        "album": "to",
        "label": "Recordeep",
        "year": 2005,
        "genre": "Techno",
        "producer": "Adam A",
        "key": "12A",
        "bpm": 105
    },
    {
        "title": "great",
        "artist": "Etapp Kyle",
        "album": "to",
        "label": "Recordeep",
        "year": 2005,
        "genre": "Techno",
        "producer": "Adam A",
        "key": "8B",
        "bpm": 107
    },
    {
        "title": "pleasure.",
        "artist": "Etapp Kyle",
        "album": "distinguish.",
        "label": "Porslin Records",
        "year": 1990,
        "genre": "Dub-Techno",
        "producer": "Daniel G",
        "key": "6A",
        "bpm": 107
    },
    {
        "title": "To",
        "artist": "Etapp Kyle",
        "album": "distinguish.",
        "label": "Porslin Records",
        "year": 1990,
        "genre": "Dub-Techno",
        "producer": "Andreas Carlson",
        "key": "8B",
        "bpm": 120
    },
    {
        "title": "take",
        "artist": "Etapp Kyle",
        "album": "distinguish.",
        "label": "Porslin Records",
        "year": 1990,
        "genre": "Dub-Techno",
        "producer": "Max Martin",
        "key": "8B",
        "bpm": 120
    },
    {
        "title": "a",
        "artist": "Etapp Kyle",
        "album": "distinguish.",
        "label": "Porslin Records",
        "year": 1990,
        "genre": "Dub-Techno",
        "producer": "Andreas Carlson",
        "key": "12A",
        "bpm": 105
    },
    {
        "title": "trivial",
        "artist": "Etapp Kyle",
        "album": "distinguish.",
        "label": "Porslin Records",
        "year": 1990,
        "genre": "Dub-Techno",
        "producer": "Sam B",
        "key": "7B",
        "bpm": 120
    },
    {
        "title": "example,",
        "artist": "Michael",
        "album": "In",
        "label": "Porslin Records",
        "year": 2000,
        "genre": "Dub-Techno",
        "producer": "Adam A",
        "key": "6A",
        "bpm": 120
    },
    {
        "title": "which",
        "artist": "Michael",
        "album": "In",
        "label": "Porslin Records",
        "year": 2000,
        "genre": "Dub-Techno",
        "producer": "Andreas Carlson",
        "key": "8B",
        "bpm": 105
    },
    {
        "title": "of",
        "artist": "Michael",
        "album": "In",
        "label": "Porslin Records",
        "year": 2000,
        "genre": "Dub-Techno",
        "producer": "Sam B",
        "key": "8B",
        "bpm": 100
    },
    {
        "title": "us",
        "artist": "Michael",
        "album": "In",
        "label": "Porslin Records",
        "year": 2000,
        "genre": "Dub-Techno",
        "producer": "Adam A",
        "key": "6A",
        "bpm": 107
    },
    {
        "title": "ever",
        "artist": "Michael",
        "album": "In",
        "label": "Porslin Records",
        "year": 2000,
        "genre": "Dub-Techno",
        "producer": "Max Martin",
        "key": "6A",
        "bpm": 120
    },
    {
        "title": "undertakes",
        "artist": "Michael",
        "album": "a",
        "label": "Star Dub",
        "year": 2000,
        "genre": "Acid",
        "producer": "Max Martin",
        "key": "12A",
        "bpm": 107
    },
    {
        "title": "laborious",
        "artist": "Michael",
        "album": "a",
        "label": "Star Dub",
        "year": 2000,
        "genre": "Acid",
        "producer": "Martin Solveig",
        "key": "8B",
        "bpm": 105
    },
    {
        "title": "physical",
        "artist": "Michael",
        "album": "a",
        "label": "Star Dub",
        "year": 2000,
        "genre": "Acid",
        "producer": "Max Martin",
        "key": "6A",
        "bpm": 100
    },
    {
        "title": "exercise,",
        "artist": "Michael",
        "album": "a",
        "label": "Star Dub",
        "year": 2000,
        "genre": "Acid",
        "producer": "LRG",
        "key": "8B",
        "bpm": 100
    },
    {
        "title": "except",
        "artist": "Michael",
        "album": "a",
        "label": "Star Dub",
        "year": 2000,
        "genre": "Acid",
        "producer": "Sam B",
        "key": "7B",
        "bpm": 100
    },
    {
        "title": "to",
        "artist": "Michael",
        "album": "free",
        "label": "Porslin Records",
        "year": 1995,
        "genre": "Acid",
        "producer": "LRG",
        "key": "6A",
        "bpm": 105
    },
    {
        "title": "obtain",
        "artist": "Michael",
        "album": "free",
        "label": "Porslin Records",
        "year": 1995,
        "genre": "Acid",
        "producer": "LRG",
        "key": "6A",
        "bpm": 100
    },
    {
        "title": "some",
        "artist": "Michael",
        "album": "free",
        "label": "Porslin Records",
        "year": 1995,
        "genre": "Acid",
        "producer": "Max Martin",
        "key": "12A",
        "bpm": 105
    },
    {
        "title": "advantage",
        "artist": "Michael",
        "album": "free",
        "label": "Porslin Records",
        "year": 1995,
        "genre": "Acid",
        "producer": "Adam A",
        "key": "8B",
        "bpm": 105
    },
    {
        "title": "from",
        "artist": "Michael",
        "album": "free",
        "label": "Porslin Records",
        "year": 1995,
        "genre": "Acid",
        "producer": "Adam A",
        "key": "7B",
        "bpm": 120
    },
    {
        "title": "it?",
        "artist": "Michael",
        "album": "hour,",
        "label": "Recordeep",
        "year": 2005,
        "genre": "Minimal House",
        "producer": "Max Martin",
        "key": "12A",
        "bpm": 120
    },
    {
        "title": "But",
        "artist": "Michael",
        "album": "hour,",
        "label": "Recordeep",
        "year": 2005,
        "genre": "Minimal House",
        "producer": "Max Martin",
        "key": "7B",
        "bpm": 120
    },
    {
        "title": "who",
        "artist": "Michael",
        "album": "hour,",
        "label": "Recordeep",
        "year": 2005,
        "genre": "Minimal House",
        "producer": "Daniel G",
        "key": "6A",
        "bpm": 105
    },
    {
        "title": "has",
        "artist": "Michael",
        "album": "hour,",
        "label": "Recordeep",
        "year": 2005,
        "genre": "Minimal House",
        "producer": "Andreas Carlson",
        "key": "12A",
        "bpm": 100
    },
    {
        "title": "any",
        "artist": "Michael",
        "album": "hour,",
        "label": "Recordeep",
        "year": 2005,
        "genre": "Minimal House",
        "producer": "Adam A",
        "key": "12A",
        "bpm": 100
    },
    {
        "title": "right",
        "artist": "Michael",
        "album": "when",
        "label": "Echochord",
        "year": 1995,
        "genre": "Dub-Techno",
        "producer": "Max Martin",
        "key": "7B",
        "bpm": 120
    },
    {
        "title": "to",
        "artist": "Michael",
        "album": "when",
        "label": "Echochord",
        "year": 1995,
        "genre": "Dub-Techno",
        "producer": "LRG",
        "key": "7B",
        "bpm": 107
    },
    {
        "title": "find",
        "artist": "Michael",
        "album": "when",
        "label": "Echochord",
        "year": 1995,
        "genre": "Dub-Techno",
        "producer": "Adam A",
        "key": "6A",
        "bpm": 120
    },
    {
        "title": "fault",
        "artist": "Dave Chappelle",
        "album": "when",
        "label": "Echochord",
        "year": 1995,
        "genre": "Dub-Techno",
        "producer": "Max Martin",
        "key": "8B",
        "bpm": 105
    },
    {
        "title": "with",
        "artist": "Dave Chappelle",
        "album": "when",
        "label": "Echochord",
        "year": 1995,
        "genre": "Dub-Techno",
        "producer": "Max Martin",
        "key": "8B",
        "bpm": 100
    },
    {
        "title": "a",
        "artist": "Dave Chappelle",
        "album": "our",
        "label": "Star Dub",
        "year": 1995,
        "genre": "Techno",
        "producer": "Andreas Carlson",
        "key": "8B",
        "bpm": 105
    },
    {
        "title": "man",
        "artist": "Dave Chappelle",
        "album": "our",
        "label": "Star Dub",
        "year": 1995,
        "genre": "Techno",
        "producer": "Martin Solveig",
        "key": "7B",
        "bpm": 120
    },
    {
        "title": "who",
        "artist": "Dave Chappelle",
        "album": "our",
        "label": "Star Dub",
        "year": 1995,
        "genre": "Techno",
        "producer": "LRG",
        "key": "12A",
        "bpm": 100
    },
    {
        "title": "chooses",
        "artist": "Dave Chappelle",
        "album": "our",
        "label": "Star Dub",
        "year": 1995,
        "genre": "Techno",
        "producer": "Sam B",
        "key": "12A",
        "bpm": 107
    },
    {
        "title": "to",
        "artist": "Dave Chappelle",
        "album": "our",
        "label": "Star Dub",
        "year": 1995,
        "genre": "Techno",
        "producer": "Adam A",
        "key": "6A",
        "bpm": 120
    },
    {
        "title": "enjoy",
        "artist": "Dave Chappelle",
        "album": "power",
        "label": "Star Dub",
        "year": 2000,
        "genre": "Dub-Techno",
        "producer": "Sam B",
        "key": "6A",
        "bpm": 107
    },
    {
        "title": "a",
        "artist": "Dave Chappelle",
        "album": "power",
        "label": "Star Dub",
        "year": 2000,
        "genre": "Dub-Techno",
        "producer": "Daniel G",
        "key": "7B",
        "bpm": 120
    },
    {
        "title": "pleasure",
        "artist": "Dave Chappelle",
        "album": "power",
        "label": "Star Dub",
        "year": 2000,
        "genre": "Dub-Techno",
        "producer": "LRG",
        "key": "8B",
        "bpm": 120
    },
    {
        "title": "that",
        "artist": "Dave Chappelle",
        "album": "power",
        "label": "Star Dub",
        "year": 2000,
        "genre": "Dub-Techno",
        "producer": "Martin Solveig",
        "key": "7B",
        "bpm": 100
    },
    {
        "title": "has",
        "artist": "Dave Chappelle",
        "album": "power",
        "label": "Star Dub",
        "year": 2000,
        "genre": "Dub-Techno",
        "producer": "Andreas Carlson",
        "key": "8B",
        "bpm": 105
    },
    {
        "title": "no",
        "artist": "Dave Chappelle",
        "album": "of",
        "label": "Star Dub",
        "year": 1995,
        "genre": "House",
        "producer": "LRG",
        "key": "6A",
        "bpm": 100
    },
    {
        "title": "annoying",
        "artist": "Dave Chappelle",
        "album": "of",
        "label": "Star Dub",
        "year": 1995,
        "genre": "House",
        "producer": "Daniel G",
        "key": "7B",
        "bpm": 100
    },
    {
        "title": "consequences,",
        "artist": "Dave Chappelle",
        "album": "of",
        "label": "Star Dub",
        "year": 1995,
        "genre": "House",
        "producer": "Adam A",
        "key": "8B",
        "bpm": 100
    },
    {
        "title": "or",
        "artist": "Dave Chappelle",
        "album": "of",
        "label": "Star Dub",
        "year": 1995,
        "genre": "House",
        "producer": "Sam B",
        "key": "6A",
        "bpm": 120
    },
    {
        "title": "one",
        "artist": "Dave Chappelle",
        "album": "of",
        "label": "Star Dub",
        "year": 1995,
        "genre": "House",
        "producer": "LRG",
        "key": "6A",
        "bpm": 107
    },
    {
        "title": "who",
        "artist": "Dave Chappelle",
        "album": "choice",
        "label": "Porslin Records",
        "year": 1995,
        "genre": "Techno",
        "producer": "Martin Solveig",
        "key": "6A",
        "bpm": 105
    },
    {
        "title": "avoids",
        "artist": "Dave Chappelle",
        "album": "choice",
        "label": "Porslin Records",
        "year": 1995,
        "genre": "Techno",
        "producer": "LRG",
        "key": "8B",
        "bpm": 100
    },
    {
        "title": "a",
        "artist": "Dave Chappelle",
        "album": "choice",
        "label": "Porslin Records",
        "year": 1995,
        "genre": "Techno",
        "producer": "Andreas Carlson",
        "key": "7B",
        "bpm": 105
    },
    {
        "title": "pain",
        "artist": "Dave Chappelle",
        "album": "choice",
        "label": "Porslin Records",
        "year": 1995,
        "genre": "Techno",
        "producer": "Max Martin",
        "key": "12A",
        "bpm": 120
    },
    {
        "title": "that",
        "artist": "Dave Chappelle",
        "album": "choice",
        "label": "Porslin Records",
        "year": 1995,
        "genre": "Techno",
        "producer": "Sam B",
        "key": "8B",
        "bpm": 120
    },
    {
        "title": "produces",
        "artist": "Dave Chappelle",
        "album": "is",
        "label": "Star Dub",
        "year": 2005,
        "genre": "House",
        "producer": "Adam A",
        "key": "7B",
        "bpm": 105
    },
    {
        "title": "no",
        "artist": "Coop-Victor",
        "album": "is",
        "label": "Star Dub",
        "year": 2005,
        "genre": "House",
        "producer": "Daniel G",
        "key": "12A",
        "bpm": 107
    },
    {
        "title": "resultant",
        "artist": "Coop-Victor",
        "album": "is",
        "label": "Star Dub",
        "year": 2005,
        "genre": "House",
        "producer": "LRG",
        "key": "6A",
        "bpm": 120
    }
];